### ISSUE TITLE
LovePlay-UIKit-SDAutoLayout 与  LovePlay-UIKit  有什么区别吗？

### ISSUE THREAD

**Issue by sdfasffsdf** [YunsChou/LovePlay#1]
LovePlay-UIKit-SDAutoLayout 与  LovePlay-UIKit  有什么区别吗？

**Comment by YunsChou** [comment]
可查看README【2017-02-15 更新】说明

LovePlay-UIKit-SDAutoLayout版本：当初想尝试轻量级布局框架SDAutoLayout，后来发现SDAutoLayout有Bug（已提交给作者，是否修复目前没有关注），导致部分控件布局有小瑕疵的版本。

LovePlay-UIKit版本：使用Masonry进行布局，修复LovePlay-UIKit-SDAutoLayout版本的瑕疵，功能无差别。
